# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [2]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[X[i][j] + Y[i][j]  
    for j in range(len(X[0]))] 
          for i in range(len(X))]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


### 2. Write a Python Program to Multiply Two Matrices?

In [4]:
import numpy as np

A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
 
# result will be 3x4
 
result= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]
 
result = np.dot(A,B)
 
for r in result:
    print(r)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


### 3. Write a Python Program to Transpose a Matrix?

In [6]:
import numpy as np
              
A= np.matrix('[4, 1; 12, 3]')
              
geek = A.transpose()
    
print(geek)

[[ 4 12]
 [ 1  3]]



### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [7]:
my_str = input("Enter a string: ")  
# breakdown the string into a list of words  
words = my_str.split()  
# sort the list  
words.sort()  
# display the sorted words  
for word in words:  
   print(word)

Enter a string: I am Vinod Kumar
I
Kumar
Vinod
am


### 5. Write a Python Program to Remove Punctuation From a String?

In [8]:
import re
 
# initializing string
test_str = "Lerning, Full $ stack Data analyst at@ Ineuron ! "
 
# printing original string
print("The original string is : " + test_str)
 
# Removing punctuations in string
# Using regex
res = re.sub(r'[^\w\s]', '', test_str)
 
# printing result
print("The string after punctuation filter : " + res)

The original string is : Lerning, Full $ stack Data analyst at@ Ineuron ! 
The string after punctuation filter : Lerning Full  stack Data analyst at Ineuron  
